### PR TITLE
Nav bar and footer

### PR DESCRIPTION
**Pull request by RafaelCenzano**

### CODE REVIEW

**Comment by RafaelCenzano** [comment]
Merge when ur done checking. Might add more footer things. Need to create column system like bootstrap.

**Review by calee14 — CHANGES_REQUESTED** [review]
Check the navbar.html and navbar.css. On my computer it doesn't look layered or aligned properly

**Comment by RafaelCenzano** [comment]
We need a column system for footer

**Review by calee14 — CHANGES_REQUESTED** [review]
For some reason I don't see the css for the navbar anymore. Could it be something about the static folder url

**Pull request merged**
